### PR TITLE
added diffcyt & iSEE to tools.Rmd

### PR DESCRIPTION
**Pull request by HelenaLC**
I've not touched people/publication/teaching.html, but they showed up when I committed. Also I got a warning when rendering the page... 
```
[WARNING] This document format requires a nonempty <title> element.
  Please specify either 'title' or 'pagetitle' in the metadata.
  Falling back to 'README.utf8'
```
Maybe it's my R or package versions and someone should re-render before finalising?

### CODE REVIEW

**Comment by csoneson** [comment]
I think the modifications to the "untouched" files are ok, looks like it's just something with the headers Did you run `render_site` with `encoding = "UTF-8"`?

I would put `iSEE` under R packages rather than under web applications though, since it is launched from an R session and requires the user to provide the input data that way. Otherwise, looks fine to me.

**Comment by HelenaLC** [comment]
* Yes, I was unsure about where to put it. I moved iSEE to R packages.
* Also updated the description for CATALYST.

**Comment by csoneson** [comment]
Ok, looks good to me. @lmweber, please approve and merge if you are happy with it.

**Comment by lmweber** [comment]
Thanks for adding `diffcyt`!

I pulled the branch and re-rendered it to check the issue with the HTML files. After re-rendering, they were back to how they were previously, so I think it was something to do with your R setup. Maybe updating R and the `rmarkdown` package will fix it. I also used `rmarkdown::render_site(encoding = "UTF-8")` as Charlotte suggested.

I will push an update with the re-rendered HTML files so we minimize changes to the `master` branch. I also added the `HDCytoData` package while I was at it.

@HelenaLC could you please check my changes after I have sent my commit, especially the addition of `HDCytoData`. If you are happy with it, we can merge it. Thanks!

We could also think about somehow distinguishing `Software` and `Data` resources (e.g. with subheadings under `R packages`). Not sure yet but thought I would suggest it and see what everyone thinks.

**Comment by markrobinsonuzh** [comment]
Thanks for all this!

@lmweber @HelenaLC What do you think about a split into:
- "R packages"
- "Data packages/resources"
- "Web applications"

"Data resources" is meant to be general .. and for example should include 'conquer', 'HDCytoData', but also the collection of benchmarks (http://imlspenticton.uzh.ch/robinson_lab/benchmark_collection/), some of the FlowRepository repos we made.  I'm thinking more for benchmarks that we have created and not to include all the repos that are associated/made with collaborators for experimental data (ArrayExpress ..). But, if I recall correctly, we did make an ArrayExpress repo with simulated data, so should include that one.

Taking this idea further, would it also be worth highlighting all the extra repos that we have that contain code to reproduce things?  I feel like this is a big part of the "output" of the lab and these seem to be well-utilized. Of course, they are already mentioned in the 'Publications' tab, but to me, it wouldn't hurt to list them all here too.

Thoughts?

**Comment by csoneson** [comment]
I think that the split into the three categories makes a lot of sense. 

Just one thought on the last suggestion: I agree that the GitHub repos are important output of our work, and it is nice that they are being used by others. However, as I see it, one major difference compared to the rest of the resources is that they are not "maintained", in the sense that they will not be guaranteed to work with new versions of R and packages, but rather represent a snapshot at the time of the corresponding publication, to reproduce the results in there (and they are of course tightly linked to the paper). This may need to be emphasised somehow.

**Comment by lmweber** [comment]
I like the idea of an additional category for "Data Packages / Resources". I could add my FlowRepositories here.

I think an additional category for other major repositories would also be good, even if they are a snapshot as at the time of publication. I could include the `cytometry-clustering-comparison` repository here, which a lot of people have been accessing. We could call it something like "Reproducibility / Other Repositories"; then in the description we could mention what each one is for (e.g. "R scripts to reproduce analyses and figures in...".

**Comment by HelenaLC** [comment]
Ok. I did a split into 4 categories to see how it looks & reordered/added everything as mentioned above!

**Comment by markrobinsonuzh** [comment]
Sweet, thanks for all this.  Give me some time and I'll add some links to this page .. then, someone can review before we merge all this.

**Comment by markrobinsonuzh** [comment]
OK, had a crack at adding some extra links.  I simplified the top heading to "resources" and simplified the sub-headings to "R packages", "Data resources", "Web applications", "Other resources" .. what do you think?

**Comment by csoneson** [comment]
I think this looks nice! Just added a couple more GitHub repos, and a few missing links.

**Pull request merged**
