### PR TITLE
reto's paper pub'd

### PR DESCRIPTION
**Pull request by markrobinsonuzh**

### CODE REVIEW

**Comment by sorjuela** [comment]
just noticed Will is missing in the alumni section

**Comment by markrobinsonuzh** [comment]
thanks @sorjuela .. added will to alumni now.

**Review by retogerber — APPROVED** [review]

**Comment by csoneson** [comment]
Looks like it's added an extra copy of the ARMOR paper (with a different PMID).

**Comment by markrobinsonuzh** [comment]
@csoneson that is indeed weird .. it appears to have 2 PMIDs (1 DOI):

https://pubmed.ncbi.nlm.nih.gov/33877351/
https://pubmed.ncbi.nlm.nih.gov/31088905/

**Comment by csoneson** [comment]
Yes - if I remember correctly the same happened to the `diffcyt` paper (although now it seems that one of those PMIDs (31925006) is gone). I have no idea why this would happen.

**Pull request merged**
