### PR TITLE
update tools, pub, word cloud with damefinder

### PR DESCRIPTION
**Pull request by sorjuela**

### CODE REVIEW

**Comment by HelenaLC** [comment]
I think you forgot to add the sticker? (can't see it in `/stickers` & it doesn't show up when I open `index.html` and navigate to "Resources").

**Comment by HelenaLC** [comment]
Stickers shows up now! Otherwise, maybe you can also add the Software link behind the publications, for consistency with all the others? Then I'll merge :)

**Comment by markrobinsonuzh** [comment]
While we are doing this, it'd be good if we can add this "publication" at the same time:
https://www.ncbi.nlm.nih.gov/pubmed/31597556

I would've thought that it would come up automatically, but it might've just appeared on PubMed.

**Comment by markrobinsonuzh** [comment]
Just tested it. If you rebuild now, it will grab the editorial. So, if @sorjuela can add the links within `biorxiv_software`, rebuild, check in, it should be good to go.

**Pull request merged**
