### PR TITLE
Pubwordcloud

### PR DESCRIPTION
**Pull request by csoneson**
Word cloud of publication abstracts

### CODE REVIEW

**Comment by markrobinsonuzh** [comment]
Super nice!

Couple things I did:
- I moved the image to the top of the page and added a caption
- I changed it so that the image output goes to /img/ directory

One other thought:
- The image is "big": 1.2MB .. would it make sense to make it a SVG and probably then it'd be tiny and would still scale well.  I haven't done this, though.

**Comment by csoneson** [comment]
Changing png to svg reduced the size from 1.2MB to 700KB

**Comment by markrobinsonuzh** [comment]
That's weird.  When I create a PDF, it is 8KB.  If I take that PDF and use a web PDF->SVG converter, it is 17KB.  That's a long way from 700KB, so what is up with R's svg() ?  Will investigate some more.

**Comment by markrobinsonuzh** [comment]
Gonna try `svglite`: https://blog.rstudio.com/2015/12/10/svglite-1-0-0/

**Comment by markrobinsonuzh** [comment]
OK, SVG is 34KB now. All good from my side!

**Comment by markrobinsonuzh** [comment]
Yes, maybe, I don't know.
```(base) IMLS-NBM-MR01:robinsonlabuzh.github.io mark$ ls site_libs/font-awesome-5.0.13/
css	fonts	js
```
Should I check these in?

**Comment by lmweber** [comment]
I just tried this too because I thought the `svg` size thing was interesting.

Using `svg` gave me a bunch of library errors. I tried `pdf` instead, which turned out as 8 KB and seems to look fine. Maybe using `pdf` is simpler here? Not sure if it affected the fonts.

**Comment by lmweber** [comment]
The library errors were related to `cairo.so`.

**Comment by csoneson** [comment]
The `site_libs` folder is already checked is, so yeah, I guess that if something changed inside it, that could be good to check in too so that it stays the same regardless of who renders the site

**Comment by markrobinsonuzh** [comment]
OK, added now!

**Comment by csoneson** [comment]
Ok, I'm merging since it's approved

**Pull request merged**
