### PR TITLE
Muscat sticker update pubs

### PR DESCRIPTION
**Pull request by HelenaLC**
- added muscat sticker to `stickers` and `tools.Rmd`
- added CS, PLG, MDR as `muscat` authors in `tools.Rmd`
- added "Helena L. Crowell" to `publications.Rmd` for highlighting
- updated wordcloud `img/abstracts_pubmed_wordcloud.svg`
> committed only `tools.Rmd/.html`, `publications.Rmd/.html`, and `img/abstracts_pubmed_wordcloud.svg`

### CODE REVIEW

**Comment by csoneson** [comment]
Shouldn't the "Software" link go to the package instead of the comparison GitHub repo? Otherwise looks good to me.

**Comment by csoneson** [comment]
I noticed the nanopore paper was also included in this PR - to keep things consistent in when they show up on the website, if you don't mind, I'll add a commit to this branch that removes the corresponding preprint.

**Comment by HelenaLC** [comment]
Not sure what you mean- the sticker & package link to `muscat` repo; other resources links to `muscat-comparison`. Am I missing something? – Of course, you can do a PR.

**Comment by csoneson** [comment]
It's not in this PR, but I meant https://github.com/robinsonlabuzh/robinsonlabuzh.github.io/blob/6f239789cb1ba40eaf0ea9ac0b145f8bbe437f19/publications.Rmd#L65 - I think this should point to the package repo. I'll add my commit for the nanopore paper shortly.

**Comment by HelenaLC** [comment]
iSEE, you were referring to the Publications tab, not Resources. I just committed a fix for the link to the package.

**Comment by csoneson** [comment]
Ok, just pushed my updates

**Comment by HelenaLC** [comment]
Okay, I review them... but can't merge so... whenever you're bored :)

**Pull request merged**
