### PR TITLE
minor updates for cv mostly

### PR DESCRIPTION
**Pull request by markrobinsonuzh**

### CODE REVIEW

**Comment by markrobinsonuzh** [comment]
@imallona @peicai not at all urgent, but just made some updates to the publications / people on the website.

**Comment by markrobinsonuzh** [comment]
And I busted the people.html build .. hold on.

**Comment by markrobinsonuzh** [comment]
better now.

**Comment by peicai** [comment]
Thanks for the update! It looks good. Perhaps I should also add DESpace to the resources -> R packages?

**Comment by peicai** [comment]
Maybe also add Jose F Carreño as alumni?

**Comment by markrobinsonuzh** [comment]
@peicai Yes, do we have a sticker for DESpace? That would be good to add to the tools page. José is still sorta here, but we don't always add interns to our list anyways.

**Comment by markrobinsonuzh** [comment]
And, if we do have a sticker, we can add it to this PR actually if you check out the `short_update_2024` branch.

**Comment by peicai** [comment]
Yes, we do have a sticker for DESpace. I added DESpace to the resources page.

**Pull request merged**
