### PR TITLE
somewhat large update: bunch of preprints now pub'd

### PR DESCRIPTION
**Pull request by markrobinsonuzh**

### CODE REVIEW

**Review by SimoneTiberi — APPROVED** [review]
Thanks a lot for adding a lot of recent material (distinct, DESpace, book chapter, etc...)!

I am terrible at spotting mistakes, but I checked carefully and it seems all good to me.

**Review by SimoneTiberi — APPROVED** [review]
Thanks a lot for adding a lot of recent material (distinct, DESpace, book chapter, etc...)!

I am terrible at spotting mistakes, but I checked carefully and it seems all good to me.

**Review by peicai — COMMENTED** [review]
Thank you so much for updating.

Only one comment, in `publications.Rmd` file and in line 104, the link to Zenodo seems wrong. It should be 7829817 instead of 5960321.
c(doi = "10.1101/2023.04.17.537189", data = "https://doi.org/10.5281/zenodo.7829817"),

**Review by almutlue — APPROVED** [review]
Looks good, DESpace should probably also be added to resources -> R packages?

**Pull request merged**
