### PR TITLE
distinct added

### PR DESCRIPTION
**Pull request by SimoneTiberi**
I added distinct preprint & sticker.
I also modified my description (people.Rmd file).

### CODE REVIEW

**Comment by supermaxiste** [comment]
Overall changes look fine, you forgot to render the HTML to see how the result looks like. From the homepage README:

> Once you've cloned the repo, created a branch to make changes on, have all the packages installed, updating the website is done via the following commands (in R):
> ```
> Sys.setlocale(category = "LC_ALL", locale = "en_US.UTF-8")
> rmarkdown::render_site(encoding = "UTF-8")
> ```
> Then once you are happy with the look of the website, commit and push the files changed (RMD + HTML + any graphics) back to your branch, and send a pull request

**Comment by markrobinsonuzh** [comment]
I added the rendered HTMLs and the new SVG. Does everything look ok?

**Comment by SimoneTiberi** [comment]
Thanks Mark; I was struggling installing all packages needed to render.

Publications and resources are fine, but `people` starts with Alumni: I'll check what I screwed up.

**Comment by markrobinsonuzh** [comment]
OK, committed a fix for that. Not sure why that part changed.
Look ok now?

**Comment by SimoneTiberi** [comment]
Looks good now, many thanks for fixing the issue and for rendering it Mark!

**Pull request merged**
