### PR TITLE
added stickers and links to fionas packages and armor

### PR DESCRIPTION
**Pull request by sorjuela**
I'm not sure where to add ARMOR, so I made a new section called "Pipelines". Also not sure where to put the sticker, so I put it under the R stickers. I also added Fiona's stickers if you think its ok to add them

### CODE REVIEW

**Comment by markrobinsonuzh** [comment]
Quick thought: Would ARMOR be happy under "Other resources" ? Or, if it still should be Pipelines, should we also move "cytofWorkflow" to it? I don't know if we'll do that many pipelines in the future and I don't really want just a single entry.

**Comment by sorjuela** [comment]
I guess it's ok. "other resources" just seemed like code to reproduce previous analysis. But should be ok

**Comment by markrobinsonuzh** [comment]
@sorjuela so, you will rearrange to have ARMOR under Other resources and re-commit? And also, can we remove `teaching.Rmd` and `teaching.html` from the commit? I don't think those need to be changed here.

**Comment by sorjuela** [comment]
I added the `teaching.Rmd` because I added a line between the sections *Courses offered at UZH* and *
External courses*, I think it looks nicer :)

**Comment by sorjuela** [comment]
do you think the sticker is ok were it is now?

**Comment by markrobinsonuzh** [comment]
the ARMOR sticker is on it's own. I think it'd be fine to stick it in the row above, if possible and we'll just keep adding. there are 9 stickers on the first row, we could shorten that to 6 (?) if it looks fine.

Thought (not strictly necessary but while we are here): would it be worth linking each sticker image to either the bioconductor package or github repo?

**Comment by sorjuela** [comment]
I made it work for 6 stickers per row by making them bigger, and added link to them.

**Pull request merged**
