### PR TITLE
Lukas update bio; add code for links to websites/Twitter/GitHub

### PR DESCRIPTION
**Pull request by lmweber**
Updating my bio.

I also added code to add links to websites, Twitter, and GitHub (see the beginning of the code block for my bio). This code can be copy-pasted to the other blocks for anyone else who wants to add these links. The 'website' part is commented out for me, since I don't have a website.

I included 'Font Awesome' (FA) icons using the same setup as previously for the `newlines`; using `gsub` to substitute the HTML code for the icons at the very end. This is because `kable` destroys the HTML tags if it sees them (it converts the `<` and `>` symbols), so they need to be substituted at the very end. Luckily `kable` simply outputs text, so this works.

### CODE REVIEW

**Comment by csoneson** [comment]
Looks good to me. For the html tags, can you solve it just by adding `escape = FALSE` to the `kable()` call?

**Comment by lmweber** [comment]
Yes, this has worked! With `escape = FALSE` in the `kable()` call, you can include HTML code directly, e.g. `<br>` for the linebreaks (`\n` still doesn't work, but `<br>` is fine too).

Thanks, this is much simpler! I will send another commit to replace all the HTML code for linebreaks and FA icons.

**Comment by lmweber** [comment]
Ok this is updated now. @csoneson 's suggestion has simplified it quite a bit. People can now add linebreaks and FA icons more easily.

@markrobinsonuzh : if you merge this later, could you please merge it without squashing? Then I can find my commits with the HTML variables and `gsub` setup more easily in future, in case I need to set up a similar system for something else. If we squash it, I think the intermediate commits will be gone.

(I think in general I prefer merging without squashing, since it lets people keep track of their work more easily. It does make the commit history a bit longer, but I think this is usually ok.)

**Comment by markrobinsonuzh** [comment]
I still prefer squash-and-merge and will stick to that policy --> more concise, less clutter and you will still be able to see the `gsub` changes you made.

**Pull request merged**
