### PR TITLE
Add meta-analysis preprint; few adjustments

### PR DESCRIPTION
**Pull request by markrobinsonuzh**

### CODE REVIEW

**Comment by plger** [comment]
`people.html` is messed up for me locally (each person takes a lot of vertical space, as a consequence of which the photos are repeated). Looking at the changes in the Rmd however I can't spot anything that would have caused this...

**Comment by markrobinsonuzh** [comment]
@plger hmm, that's weird. i don't get it. my local version looks fine. did you rebuild it yourself?

**Comment by imallona** [comment]
@plger might be related to your kableExtra https://github.com/robinsonlabuzh/robinsonlabuzh.github.io/pull/189/commits/c6228d0cfeed692d55a26764a01ac8c1271a4d94

**Comment by plger** [comment]
False alarm, as usual I did something stupid (I didn't notice the checkout hadn't worked due to old uncommitted stuff), sorry for the loss of time!
All looks good to me

**Review by plger — APPROVED** [review]

**Comment by markrobinsonuzh** [comment]
thanks!

**Pull request merged**
